global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "haste-crm"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # hasteCRM API metrics
  - job_name: "haste-api"
    metrics_path: "/metrics/prometheus"
    static_configs:
      - targets: ["api:3333"]
    scrape_interval: 30s

  # PostgreSQL Exporter
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis Exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Docker containers (cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Nginx (if using)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
